Web Projesi Ödev/WebApplication1/WebApplication1/Controllers/BaliksController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebApplication1.Models;
using WebApplication1.data;

namespace WebApplication1.Controllers
{
    public class BaliksController : Controller
    {
        private readonly KediDbContext _context;

        public BaliksController(KediDbContext context)
        {
            _context = context;
        }

        // GET: Baliks
        public async Task<IActionResult> Index()
        {
            return View(await _context.Balik.ToListAsync());
        }

        // GET: Baliks/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var balik = await _context.Balik
                .FirstOrDefaultAsync(m => m.Id == id);
            if (balik == null)
            {
                return NotFound();
            }

            return View(balik);
        }

        // GET: Baliks/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Baliks/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,fiyat,adi")] Balik balik)
        {
            if (ModelState.IsValid)
            {
                _context.Add(balik);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(balik);
        }

        // GET: Baliks/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var balik = await _context.Balik.FindAsync(id);
            if (balik == null)
            {
                return NotFound();
            }
            return View(balik);
        }

        // POST: Baliks/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,fiyat,adi")] Balik balik)
        {
            if (id != balik.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(balik);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BalikExists(balik.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(balik);
        }

        // GET: Baliks/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var balik = await _context.Balik
                .FirstOrDefaultAsync(m => m.Id == id);
            if (balik == null)
            {
                return NotFound();
            }

            return View(balik);
        }

        // POST: Baliks/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var balik = await _context.Balik.FindAsync(id);
            _context.Balik.Remove(balik);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool BalikExists(int id)
        {
            return _context.Balik.Any(e => e.Id == id);
        }
    }
}

Web Projesi Ödev/WebApplication1/WebApplication1/Controllers/KedisController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebApplication1.Models;
using WebApplication1.data;

namespace WebApplication1.Controllers
{
    public class KedisController : Controller
    {
        private readonly KediDbContext _context;

        public KedisController(KediDbContext context)
        {
            _context = context;
        }

        // GET: Kedis
        public async Task<IActionResult> Index()
        {
            return View(await _context.Kedi.ToListAsync());
        }

        // GET: Kedis/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var kedi = await _context.Kedi
                .FirstOrDefaultAsync(m => m.Id == id);
            if (kedi == null)
            {
                return NotFound();
            }

            return View(kedi);
        }

        // GET: Kedis/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Kedis/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,fiyat,adi")] Kedi kedi)
        {
            if (ModelState.IsValid)
            {
                _context.Add(kedi);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(kedi);
        }

        // GET: Kedis/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var kedi = await _context.Kedi.FindAsync(id);
            if (kedi == null)
            {
                return NotFound();
            }
            return View(kedi);
        }

        // POST: Kedis/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,fiyat,adi")] Kedi kedi)
        {
            if (id != kedi.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(kedi);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!KediExists(kedi.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(kedi);
        }

        // GET: Kedis/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var kedi = await _context.Kedi
                .FirstOrDefaultAsync(m => m.Id == id);
            if (kedi == null)
            {
                return NotFound();
            }

            return View(kedi);
        }

        // POST: Kedis/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var kedi = await _context.Kedi.FindAsync(id);
            _context.Kedi.Remove(kedi);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool KediExists(int id)
        {
            return _context.Kedi.Any(e => e.Id == id);
        }
    }
}

Web Projesi Ödev/WebApplication1/WebApplication1/Controllers/KopeksController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebApplication1.Models;
using WebApplication1.data;

namespace WebApplication1.Controllers
{
    public class KopeksController : Controller
    {
        private readonly KediDbContext _context;

        public KopeksController(KediDbContext context)
        {
            _context = context;
        }

        // GET: Kopeks
        public async Task<IActionResult> Index()
        {
            return View(await _context.Kopek.ToListAsync());
        }

        // GET: Kopeks/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var kopek = await _context.Kopek
                .FirstOrDefaultAsync(m => m.Id == id);
            if (kopek == null)
            {
                return NotFound();
            }

            return View(kopek);
        }

        // GET: Kopeks/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Kopeks/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,fiyat,adi")] Kopek kopek)
        {
            if (ModelState.IsValid)
            {
                _context.Add(kopek);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(kopek);
        }

        // GET: Kopeks/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var kopek = await _context.Kopek.FindAsync(id);
            if (kopek == null)
            {
                return NotFound();
            }
            return View(kopek);
        }

        // POST: Kopeks/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,fiyat,adi")] Kopek kopek)
        {
            if (id != kopek.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(kopek);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!KopekExists(kopek.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(kopek);
        }

        // GET: Kopeks/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var kopek = await _context.Kopek
                .FirstOrDefaultAsync(m => m.Id == id);
            if (kopek == null)
            {
                return NotFound();
            }

            return View(kopek);
        }

        // POST: Kopeks/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var kopek = await _context.Kopek.FindAsync(id);
            _context.Kopek.Remove(kopek);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool KopekExists(int id)
        {
            return _context.Kopek.Any(e => e.Id == id);
        }
    }
}

Web Projesi Ödev/WebApplication1/WebApplication1/Controllers/KusController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebApplication1.Models;
using WebApplication1.data;

namespace WebApplication1.Controllers
{
    public class KusController : Controller
    {
        private readonly KediDbContext _context;

        public KusController(KediDbContext context)
        {
            _context = context;
        }

        // GET: Kus
        public async Task<IActionResult> Index()
        {
            return View(await _context.Kus.ToListAsync());
        }

        // GET: Kus/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var kus = await _context.Kus
                .FirstOrDefaultAsync(m => m.Id == id);
            if (kus == null)
            {
                return NotFound();
            }

            return View(kus);
        }

        // GET: Kus/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Kus/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,fiyat,adi")] Kus kus)
        {
            if (ModelState.IsValid)
            {
                _context.Add(kus);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(kus);
        }

        // GET: Kus/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var kus = await _context.Kus.FindAsync(id);
            if (kus == null)
            {
                return NotFound();
            }
            return View(kus);
        }

        // POST: Kus/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,fiyat,adi")] Kus kus)
        {
            if (id != kus.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(kus);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!KusExists(kus.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(kus);
        }

        // GET: Kus/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var kus = await _context.Kus
                .FirstOrDefaultAsync(m => m.Id == id);
            if (kus == null)
            {
                return NotFound();
            }

            return View(kus);
        }

        // POST: Kus/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var kus = await _context.Kus.FindAsync(id);
            _context.Kus.Remove(kus);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool KusExists(int id)
        {
            return _context.Kus.Any(e => e.Id == id);
        }
    }
}

Web Projesi Ödev/WebApplication1/WebApplication1/Views/Home/Index.cshtml
@{
     ViewData["Title"] = "Home Page";
}



<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>

</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
            <a class="navbar-brand" href="#">Hakkımızda</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="#">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/AdminLogin/Index">Admin Login</a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            Dropdown
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <li><a class="dropdown-item" href="#">Action</a></li>
                            <li><a class="dropdown-item" href="#">Another action</a></li>
                            <li><hr class="dropdown-divider"></li>
                            <li><a class="dropdown-item" href="#">Something else here</a></li>
                        </ul>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link disabled">Disabled</a>
                    </li>
                </ul>
                <form class="d-flex">
                    <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                    <button class="btn btn-outline-success" type="submit">Search</button>
                </form>
            </div>
        </div>
    </nav>
    <h1>
        <br />

    </h1>
    <div class="card-group">
        <div class="card">
            <img class="card-img-top" src="~/lib/img/bir.jpg" alt="Card image cap">
            <div class="card-body">
                <h5 class="card-title">Balık</h5>
                <p class="card-text">
                    Balıkların suda sakince yüzmelerini izlemek sağlımız açısından oldukça
                    faydalıdır. Akvaryumu izlemenin, suyun dinlendiriciliğinin de etkisiyle kan basıncını
                    düşüren ve stresi azaltan etkisi vardır. Bu nedenle de genellikle ofislerde ve evlerde
                    akvaryum bulunuyor. Hatta akvaryum yayını yapan kanalların olma nedeni de bu etkiyle
                    ilgilidir. Feng Shui sanatına göre de balıkların şans ve pozitif enerji getirdiği için
                    önemi büyüktür
                </p>
                <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
                @*    <a href="/Balik/Index" class="btn btn-primary btn-lg active" role="button" aria-pressed="true">Detaylı Bilgi</a>*@
                <a class="btn btn-primary btn-lg active" role="button" aria-pressed="true" asp-area="" asp-controller="Baliks" asp-action="Index">Detaylı Bilgi</a>

            </div>
        </div>
        <div class="card">
            <img class="card-img-top" src="~/lib/img/iki.jpg" alt="Card image cap">
            <div class="card-body">
                <h5 class="card-title">Kuş</h5>
                <p class="card-text">
                    Evcil kuş türleri genel olarak arkadaş canlısı ve sosyal yaratıklardır.
                    Sosyal canlılar olan kuşlarla kısa süre içerisinde derin bağlar kurabilirsiniz.
                    Evcil kuşlar bakıcılarına oldukça bağlıdır. Bu nedenle bakıcılarının eşyalarını da
                    tanırlar. Sadece eşyalarınızı tanımakla kalmaz, sizinle yemeğini yer ve hatta omzunuzdan
                    hiç ayrılmaz. İyi bir evcil hayvan arıyorsanız arkadaş canlısı kuşları tercih
                    edebilirsiniz.

                </p>
                <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
                @* <a href="/Kus/Index" class="btn btn-primary btn-lg active" role="button" aria-pressed="true">Detaylı Bilgi</a>*@
                <a class="btn btn-primary btn-lg active" role="button" aria-pressed="true" asp-area="" asp-controller="Kus" asp-action="Index">Detaylı Bilgi</a>

            </div>
        </div>
        <div class="card">
            <img class="card-img-top" src="~/lib/img/uc.jpg" alt="Card image cap">
            <div class="card-body">
                <h5 class="card-title">Kedi</h5>
                <p class="card-text">
                    En başta söyleyelim kediler çevre ve doğa dostu hayvanlar.
                    Acılarınız mı var? Bunlarla baş etmek için tek doğal ilaç kedi.
                    Aşk hayatım yoluna girsin istiyorsan çare kedi!
                    Çok net konuşmak istemiyoruz ama kedi sahipleri daha zeki galiba.
                    Kalp sağlığı için Canan Karatay yerine kedi!
                    Belki tüm bu saydıklarımızdan sonra bir kedi sahiplenmek istersiniz :').
                </p>
                <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
                @*<a href="/Kedi/Index" class="btn btn-primary btn-lg active" role="button" aria-pressed="true">Detaylı Bilgi</a>*@
                <a class="btn btn-primary btn-lg active" role="button" aria-pressed="true" asp-area="" asp-controller="Kedis" asp-action="Index">Detaylı Bilgi</a>
            </div>
        </div>
        <div class="card">
            <img class="card-img-top" src="~/lib/img/dort (2).jpg" alt="Card image cap"> 
            <div class="card-body">
                <h5 class="card-title">Köpek</h5>
                <p class="card-text">
                    Yer yer bazılarımızı birazcık ürkütseler de, köpeklerin harika yanları
                    saymakla bitmiyor. Bunlardan biri de dört ayaklı can dostlarımızın zihin sağlığına katkıları.
                    Şimdiye kadar konuyla ilgili yapılan neredeyse bütün bilimsel çalışmalar, bir köpekle dostça
                    bir etkileşimde bulunmanın faydalarına işaret ediyor
                </p>
                <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>

                @* <a href="/Kopek/Index" class="btn btn-primary btn-lg active" role="button" aria-pressed="true">Detaylı Bilgi</a>*@
                <a class="btn btn-primary btn-lg active" role="button" aria-pressed="true" asp-area="" asp-controller="Kopeks" asp-action="Index">Detaylı Bilgi</a>

            </div>
        </div>
</body>
</html>